//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kurier.Properties {


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class S3Settings : global::System.Configuration.ApplicationSettingsBase {

        private static S3Settings defaultInstance = ((S3Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new S3Settings())));

        public static S3Settings Default {
            get {
                return defaultInstance;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AWS_ACCESS_KEY {
            get {
                return ((string)(this["AWS_ACCESS_KEY"]));
            }
            set {
                this["AWS_ACCESS_KEY"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AWS_SECRET_KEY {
            get {
                return ((string)(this["AWS_SECRET_KEY"]));
            }
            set {
                this["AWS_SECRET_KEY"] = value;
            }
        }
    }
}
